# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 96e5a9aaae8e65dd582bad34f676d1884ca70a09e771efff4001d92f0291404be7a71098b02256f046cd749f80ca4cbce46a03b62aee243b750f73bc5d52ca04

test:
  secret_key_base: ba6270caa78cbf550376ae79b1ed5712afa44b8c45c9af94d08f7fb667b7a9379b76194e84c73cfc299ce4ed7904bd8f54a1324f0ece3e03286bdf55f98b17d3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
